name: AWS-assume-role

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [master]  

env:
  AWS_REGION: ap-southeast-2

# Permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  checks:
    runs-on: ubuntu-latest
    if: |
        (github.event_name != 'workflow_run') ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')    
    steps:
      - uses: actions/checkout@v2
      - name: Check workflow
        run: | 
          echo "🧪 Checking triggering workflow..."
          echo "[Release] ref: ${{ github.ref }} - event: ${{ github.event_name }} - conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "[Release] condition: ${{ (github.event_name != 'workflow_run') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}"
          
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ test, production ]
        region: [ ap-southeast-2, us-east-1 ]
        include:
          - region: ap-southeast-2
            bucket: ryan-shaki-3rd
          - region: us-east-1
            bucket: ryan-shaki-4th   
          # - environment: test
          #   region: ap-southeast-2
          #   bucket: ryan-shaki-3rd
          # - environment: test
          #   region: us-east-1
          #   bucket: ryan-shaki-3rd   
          # - environment: production
          #   region: ap-southeast-2
          #   bucket: ryan-shaki-4th            
          # - environment: production
          #   region: us-east-1
          #   bucket: ryan-shaki-4th
    env:
      BUCKET: ${{ matrix.bucket }}
      region: ${{ matrix.region }}
    needs: checks
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050274331:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: STS GetCallerIdentity
        run: |-
          aws sts get-caller-identity

          echo "env: ${{ matrix.environment }} | region: ${{ matrix.region }}"
          echo "🚀 🥎 🗿 🪣 Calling S3..."
          aws s3 ls
          echo "---"
          echo "bucket content (${{ env.BUCKET }}) in ${{ env.region }}:"
          ### aws s3api list-objects --bucket ryan-shaki-3rd
          aws s3api list-objects --bucket ${{ env.BUCKET }}
