# This is a basic workflow to check out Github Actions by me!

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          
      - name: Install Dependencies
        run: |
          echo "Installing Bundler..."
          gem install bundler
          
      - name: Install Gems
        run: |
          echo "Installing gems..."
          bundle install   
          
      - name: Run Tests
        run: |
          bundle exec rspec
