name: Setup

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: '2.7.1' # Not needed with a .ruby-version file
          bundler-cache: true

      - name: Install Dependencies
        run: |
          echo "Installing Bundler..."
          gem install bundler

      - name: Install Gems
        run: |
          echo "Installing gems..."
          bundle install

      - name: Run Tests
        run: |
          echo "🧪 Testing..."
          bundle exec rspec

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 10

  Production:
    runs-on: ubuntu-latest
    needs: [Test]
    environment:
      name: Production
      url: https://example.com
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
